# https://taskfile.dev

version: '3'

tasks:
  test:
    desc: Run tests
    sources:
      - "**/*.js"
      - "!node_modules/**"
    cmds:
      - node --test
      - scripts/test.bash
    silent: true
  fix:
    cmds:
      - task: lint
        vars:
          fix: true
  lint:
    desc: Run linters
    vars:
      fix: '{{ default "" .fix}}'
    sources:
      - "**/*.js"
      - "!node_modules/**"
    cmds:
      - biome check index.js lib{{if .fix}} --fix{{end}}