# https://taskfile.dev

version: '3'

tasks:
  fix:
    cmds:
      - task: lint
        vars:
          fix: true
  lint:
    desc: Run linters
    vars:
      fix: '{{ default "" .fix}}'
    sources:
      - "**/*.ts"
      - "!node_modules/**"
    cmds:
      - biome check src{{if .fix}} --fix{{end}}