#!/usr/bin/env bash
set -eu
set -o pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

tmpdirpath="$(mktemp -d)"
for repo_dirname in "$root_dir"/repos/*; do
  repo_name="$(basename "$repo_dirname" .git)"
  repo_dirpath="$tmpdirpath/$repo_name"
  git clone "$repo_dirname" "$repo_dirpath"
done
echo "All repositories cloned to $tmpdirpath."